# Generated by Django 5.0.1 on 2026-01-19 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveillanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_pdf', models.FileField(upload_to='reports/pdf/%Y/%m/')),
                ('generated_docx', models.FileField(blank=True, null=True, upload_to='reports/docx/%Y/%m/')),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('total_mentions', models.IntegerField(default=0)),
                ('mentions_change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_reach', models.BigIntegerField(default=0)),
                ('reach_change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sentiment_data', models.JSONField(default=dict)),
                ('emotion_data', models.JSONField(default=dict)),
                ('sources_data', models.JSONField(default=dict)),
                ('languages_data', models.JSONField(default=dict)),
                ('topics_data', models.JSONField(default=list)),
                ('hashtags_data', models.JSONField(default=list)),
                ('influencers_data', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
