# Generated by Django 5.2.11 on 2026-02-10 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_add_reach_breakdown_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Common title/keyword for all reports in this group",
                        max_length=255,
                    ),
                ),
                (
                    "generated_docx",
                    models.FileField(
                        blank=True, null=True, upload_to="reports/grouped/%Y/%m/"
                    ),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("merged_presence_passive", models.JSONField(blank=True, default=dict)),
                ("merged_presence_active", models.JSONField(blank=True, default=dict)),
                ("merged_sentiment", models.JSONField(blank=True, default=dict)),
                ("merged_emotion", models.JSONField(blank=True, default=dict)),
                ("merged_sources", models.JSONField(blank=True, default=dict)),
                ("merged_languages", models.JSONField(blank=True, default=dict)),
                ("merged_topics", models.JSONField(blank=True, default=list)),
                ("merged_hashtags", models.JSONField(blank=True, default=list)),
                ("merged_influencers", models.JSONField(blank=True, default=list)),
                ("merged_reach_breakdown", models.JSONField(blank=True, default=list)),
                ("merged_demographics", models.JSONField(blank=True, default=dict)),
                (
                    "manual_followers",
                    models.IntegerField(
                        blank=True,
                        help_text="Manual entry for followers count",
                        null=True,
                    ),
                ),
                (
                    "manual_likes",
                    models.IntegerField(
                        blank=True, help_text="Manual entry for likes count", null=True
                    ),
                ),
                (
                    "manual_shares",
                    models.IntegerField(
                        blank=True, help_text="Manual entry for shares count", null=True
                    ),
                ),
                (
                    "manual_comments",
                    models.IntegerField(
                        blank=True,
                        help_text="Manual entry for comments count",
                        null=True,
                    ),
                ),
                (
                    "manual_views",
                    models.IntegerField(
                        blank=True, help_text="Manual entry for views count", null=True
                    ),
                ),
                ("data_sources", models.JSONField(blank=True, default=dict)),
                ("included_report_types", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Group",
                "verbose_name_plural": "Report Groups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="surveillancereport",
            name="report_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_reports",
                to="reports.reportgroup",
            ),
        ),
    ]
